feat: add a tooltip after taking home and add request
Lapkipomoshi/help_paw_frontend pull request #185
Opened 2023-09-04 08:32 UTC by Klaurrr

2023-09-04 12:23 UTC, bevuxyna requested changes

2023-09-04 12:23 UTC, bevuxyna commented on src/modules/PetModule/PetModule.jsx
> +            onMouseEnter={() => {
```suggestion
            onMouseEnter={showTooltip}
```

2023-09-04 12:23 UTC, bevuxyna commented on src/modules/PetModule/PetModule.jsx
> +            onMouseLeave={() => {
```suggestion
            onMouseLeave={hideTooltip}
```

2023-09-04 12:23 UTC, bevuxyna commented on src/ui/Tooltip/Tooltip.scss
> +    top: -105px;
откуда такие большие значения отсчитывались?

2023-09-04 12:23 UTC, bevuxyna commented on src/ui/Tooltip/Tooltip.scss
> +    height: 100px;
думаю, что не стоит ограничивать высоту, т.к. может быть больше или меньше текста в других попапах

2023-09-04 12:23 UTC, bevuxyna commented on src/modules/PetModule/PetModule.jsx
> +              <p className='pet-module__tooltip-paragraph'>Вы уже отправили заявку в приют на этого питомца.</p>
**suggestion:** у нас есть стандартные стили для текста `standard-font`

2023-09-04 13:08 UTC, stillNiceTanya commented on src/modules/PetModule/styles/pet-module.scss
> +  }
suggestion(non-blocking): Есть возможность установить/настроить prettier, чтобы были единые стили на проекте?

2023-09-04 13:08 UTC, stillNiceTanya commented on src/ui/Button/Button.jsx
> +      }
suggestion(non-blocking): Было бы здорово вынести выше, для удобства читаемости

2023-09-04 13:24 UTC, Klaurrr commented on src/modules/PetModule/PetModule.jsx
> +    const fetchData = async () => {
Я пометил, что он тестовый. Чтобы показать, что с беком что-то не так

2023-09-04 13:24 UTC, Klaurrr commented on src/modules/PetModule/PetModule.jsx
> +    const fetchData = async () => {
вынесу)

2023-09-04 13:25 UTC, Klaurrr commented on src/pages/App/App.jsx
> -              exact path='/sign-in'
Потому что когда у тебя путь /abd/id/adb/id и нужно получить два id, нужно чтобы они были по-разному названы. В моем компоненте я должен был получить Id приюта и id питомца

2023-09-04 13:25 UTC, Klaurrr commented on src/pages/App/App.jsx
> -              exact path='/sign-in'
У меня при сохранении автоматически притер срабатывает и он так строчки двигает(

2023-09-04 13:27 UTC, Klaurrr commented on src/ui/Tooltip/Tooltip.scss
> +    top: -105px;
Я в макете с конца отмерил,  я откуда-то могу их взять?

2023-09-04 13:27 UTC, Klaurrr commented on .github/workflows/pr_closed.yml
> +            SERVER_ENV=${{ secrets.REACT_APP_SERVER_TYPE_PROD }}
Я докер не трогал......Я не знаю, почему тут изменения какие-то

2023-09-04 13:37 UTC, bevuxyna commented on src/ui/Tooltip/Tooltip.scss
> +    top: -105px;
Я пока в макете не нашла, будут ли где-то еще такие же попапы. Тебе не попадались? 
Мне кажется, что лучше отсчитывать от кнопки позицию, потому что попап привязан именно к кнопке

2023-09-04 13:38 UTC, Klaurrr commented on src/pages/App/App.jsx
> -              exact path='/sign-in'
Это могут быть не ваши правила, а мои... Моего притира. Я постараюсь перенастроить для этого проекта его

2023-09-04 13:38 UTC, bevuxyna commented on .github/workflows/pr_closed.yml
> +            SERVER_ENV=${{ secrets.REACT_APP_SERVER_TYPE_PROD }}
а ты ветку когда создавал? просто у тебя еще столько коммитов высвечивается старых

2023-09-04 14:03 UTC, stillNiceTanya commented on src/ui/Button/Button.jsx
> +      }
поняла, если есть время - вынеси, пожалуйста😌

2023-09-04 19:29 UTC, bevuxyna commented on src/modules/PetModule/styles/pet-module.scss
> +  &__button-disabled {
эти стили уже есть у `Button`

2023-09-04 19:29 UTC, bevuxyna commented on src/modules/PetModule/styles/pet-module.scss
> +    top: -105px;
у `button-wrapper` `position relative`, т.е. если отсчитывать от кнопки, будет `top: 0`, `right: 0`

2023-09-04 19:29 UTC, bevuxyna commented on src/modules/PetModule/PetModule.jsx
> +        <div className='pet-module__button-wrapper'>
эта обертка точно нужна? можно через пропс `className` передать `position: relative`

2023-09-04 19:35 UTC, bevuxyna commented on src/ui/Tooltip/Tooltip.scss
> +    top: -105px;
Нашла на макетах 6.2.1.1.2, 6.2.2.3

2023-09-05 06:17 UTC, Klaurrr commented on src/modules/PetModule/styles/pet-module.scss
> +    top: -105px;
От отсчитывает не от кнопки, а от родительского контейнера. Если задать ему нулевые значения, он встает по середине

2023-09-05 06:20 UTC, Klaurrr commented on src/modules/PetModule/styles/pet-module.scss
> +  &__button-disabled {
Поправил

2023-09-05 06:24 UTC, Klaurrr commented on src/modules/PetModule/PetModule.jsx
> +        <div className='pet-module__button-wrapper'>
Нужна, она является связующим звеном между кнопкой и тултипом. Не совсем понимаю, кому здесь можно еще передать position: relative. position: absolute отмеряется от родителя, а не от близлежащего элемента. Если я не правильно понял, поясни пожалуйста

2023-09-05 06:28 UTC, Klaurrr commented on src/ui/Tooltip/Tooltip.scss
> +    top: -105px;
я убрал фиксированную высоту)

2023-09-05 06:40 UTC, bevuxyna approved these changes

2023-09-05 14:02 UTC, stillNiceTanya approved these changes

2023-09-06 08:34 UTC, merged